pattern_library/urls.py
from django.urls import path, re_path

from pattern_library import get_pattern_template_suffix, views

app_name = "pattern_library"
urlpatterns = [
    # UI
    re_path(r"^$", views.IndexView.as_view(), name="index"),
    re_path(
        r"^pattern/(?P<pattern_template_name>[\w./\-\\]+%s)$"
        % (get_pattern_template_suffix()),
        views.IndexView.as_view(),
        name="display_pattern",
    ),
    # iframe rendering
    re_path(
        r"^render-pattern/(?P<pattern_template_name>[\w./\-\\]+%s)$"
        % (get_pattern_template_suffix()),
        views.RenderPatternView.as_view(),
        name="render_pattern",
    ),
    # API rendering
    path("api/v1/render-pattern", views.render_pattern_api, name="render_pattern_api"),
]

pattern_library/views.py
import json

from django.http import Http404, HttpResponse
from django.template.loader import get_template
from django.utils.decorators import method_decorator
from django.utils.html import escape
from django.utils.safestring import mark_safe
from django.views.decorators.clickjacking import xframe_options_sameorigin
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import TemplateView

from pattern_library import get_base_template_names, get_pattern_base_template_name
from pattern_library.exceptions import PatternLibraryEmpty, TemplateIsNotPattern
from pattern_library.utils import (
    get_pattern_config,
    get_pattern_config_str,
    get_pattern_context,
    get_pattern_markdown,
    get_renderer,
    get_sections,
    is_pattern,
    render_pattern,
)


class IndexView(TemplateView):
    http_method_names = ("get",)
    template_name = "pattern_library/index.html"

    def first_template_from_group(self, templates):
        try:
            return templates["templates_stored"][0]
        except IndexError:
            for template_group in templates["template_groups"].values():
                return self.first_template_from_group(template_group)
        return None

    def get_first_template(self, templates):
        first_template = self.first_template_from_group(templates)
        if first_template:
            return first_template.origin.template_name

        sections = get_sections()
        if sections:
            raise PatternLibraryEmpty(
                "No templates found matching: '%s'" % str(sections)
            )
        else:
            raise PatternLibraryEmpty(
                "No 'SECTIONS' found in the 'PATTERN_LIBRARY' setting"
            )

    def get(self, request, pattern_template_name=None):
        # Get all pattern templates
        renderer = get_renderer()
        templates = renderer.get_pattern_templates()

        if pattern_template_name is None:
            # Just display the first pattern if a specific one isn't requested
            pattern_template_name = self.get_first_template(templates)

        if not is_pattern(pattern_template_name):
            raise Http404

        template = get_template(pattern_template_name)
        pattern_config = get_pattern_config(pattern_template_name)

        context = self.get_context_data()
        context["pattern_templates"] = templates
        context["pattern_template_name"] = pattern_template_name
        context["pattern_source"] = renderer.get_pattern_source(template)
        context["pattern_config"] = escape(
            get_pattern_config_str(pattern_template_name)
        )
        context["pattern_name"] = pattern_config.get("name", pattern_template_name)
        context["pattern_markdown"] = get_pattern_markdown(pattern_template_name)

        return self.render_to_response(context)


class RenderPatternView(TemplateView):
    http_method_names = ("get",)
    template_name = get_pattern_base_template_name()

    @method_decorator(xframe_options_sameorigin)
    def get(self, request, pattern_template_name=None):
        renderer = get_renderer()
        pattern_template_ancestors = renderer.get_template_ancestors(
            pattern_template_name,
            context=get_pattern_context(self.kwargs["pattern_template_name"]),
        )
        pattern_is_fragment = set(pattern_template_ancestors).isdisjoint(
            set(get_base_template_names())
        )

        try:
            rendered_pattern = render_pattern(request, pattern_template_name)
        except TemplateIsNotPattern:
            raise Http404

        if pattern_is_fragment:
            context = self.get_context_data()
            context["pattern_library_rendered_pattern"] = mark_safe(rendered_pattern)
            return self.render_to_response(context)

        return HttpResponse(rendered_pattern)


@csrf_exempt
def render_pattern_api(request):
    data = json.loads(request.body.decode("utf-8"))
    template_name = data["template_name"]
    config = data["config"]

    try:
        rendered_pattern = render_pattern(
            request, template_name, allow_non_patterns=False, config=config
        )
    except TemplateIsNotPattern:
        raise Http404

    return HttpResponse(rendered_pattern)

pattern_library/templates/pattern_library/base.html
{% load static %}
{% load pattern_library_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Django pattern library</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>♻️</text></svg>"/>
    <script type="text/javascript" src="{% static 'pattern_library/dist/bundle.js' %}"></script>
    {% pattern_library_custom_css %}
</head>

<body class="body">
    <header class="header">
        <a class="button button--close-menu js-close-menu" href="#">
            <span class="sr-only">Close menu</span>
            <svg class="icon icon--close-menu" viewBox="0 0 14 14" xmlns="http://www.w3.org/2000/svg"><path d="M14 1.41L12.59 0 7 5.59 1.41 0 0 1.41 5.59 7 0 12.59 1.41 14 7 8.41 12.59 14 14 12.59 8.41 7z" fill-rule="nonzero"/></svg>
        </a>
        <h1 class="header__title">
            <span class="sr-only">Pattern Library</span>
            {% pattern_library_site_title %}
        </h1>
    </header>
    <aside class="sidebar">
        <div class="sidebar__inner">
            <label for="js-pattern-search-input" class="sr-only">Search pattern library</label>
            <input type="text" class="sidebar__search" id="js-pattern-search-input" placeholder="Search library...">
            <div class="sidebar__search-results" id="js-pattern-search-results-container"></div>
            <nav class="sidebar__nav" id="sidebar-nav">
                <ul class="list">
                    {% for pattern_type_group, pattern_templates in pattern_templates.template_groups.items %}
                    <li class="list__item js-list-item">
                        <button class="list__button list__button--parent js-toggle-pattern">
                            <svg class="list__item-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 160 160">
                                <path d="M88 80l-48 48 16 16 64-64-64-64-16 16 48 48z" />
                            </svg>
                            {{ pattern_type_group|title }}
                        </button>
                        {% include "pattern_library/pattern_group.html" with groups=pattern_templates.template_groups %}
                    </li>
                    {% endfor %}
                </ul>
            </nav>
        </div>
    </aside>
    <main class="main">
        {% block content %}{% endblock %}
    </main>
</body>
</html>

pattern_library/templates/pattern_library/index.html
{% extends 'pattern_library/base.html' %}

{% block content %}
    <section>
        <div class="wrapper wrapper--pattern-header">
            <h3 class="heading">
                <a href="{% url 'pattern_library:render_pattern' pattern_template_name=pattern_template_name %}">
                    {{ pattern_name }}
                    <svg class="icon icon--external" viewBox="0 0 48 48" xmlns="http://www.w3.org/2000/svg"><path d="M0 0h48v48h-48z" fill="none"/><path d="M38 38h-28v-28h14v-4h-14c-2.21 0-4 1.79-4 4v28c0 2.21 1.79 4 4 4h28c2.21 0 4-1.79 4-4v-14h-4v14zm-10-32v4h7.17l-19.66 19.66 2.83 2.83 19.66-19.66v7.17h4v-14h-14z"/></svg>
                </a>
            </h3>
            <div class="wrapper wrapper--resize-buttons">
                <h4 class="heading heading--iframe-size js-iframe-size">
                    <span class="sr-only">Window sizes</span>
                </h4>
                <button class="button button--resize js-resize-iframe" data-resize="320">S</button>
                <button class="button button--resize js-resize-iframe" data-resize="768">M</button>
                <button class="button button--resize js-resize-iframe" data-resize="1024">L</button>
                <button class="button button--resize js-resize-iframe is-active" data-resize="100">Full</button>
            </div>
        </div>

        <iframe class="iframe js-iframe is-animatable" src="{% url 'pattern_library:render_pattern' pattern_template_name=pattern_template_name %}" title="Iframe pattern"></iframe>

        <div class="tabbed-content">
            <ul class="tabbed-content__list">
                <li class="tabbed-content__heading tabbed-content__heading--active">
                    <a href="#tab-1">Template source</a>
                </li>
                <li class="tabbed-content__heading">
                    <a href="#tab-2">Template config</a>
                </li>

                <li class="tabbed-content__heading">
                    <a href="#tab-3">Template docs</a>
                </li>
            </ul>

            <div class="tabbed-content__tabs">
                <div id="tab-1" class="tabbed-content__item tabbed-content__item--active">
                    <pre><code class="code django">{{ pattern_source }}</code></pre>
                </div>

                <div id="tab-2" class="tabbed-content__item">
                    <pre><code class="code yaml">{{ pattern_config }}</code></pre>
                </div>

                <div id="tab-3" class="tabbed-content__item">
                    <div class="md">{{ pattern_markdown|safe }}</div>
                </div>
            </div>
        </div>

    </section>
{% endblock %}

pattern_library/templates/pattern_library/pattern_group.html
<ul class="list list--child">
    {% for group_name, pattern_templates in groups.items %}
    <li class="list__item js-list-item">
        <button class="list__button list__button--child js-toggle-pattern">
            <svg class="list__item-icon list__item-icon--small" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 160 160">
                <path d="M88 80l-48 48 16 16 64-64-64-64-16 16 48 48z" fill="currentColor" />
            </svg>
            {{ group_name }}
        </button>
        {% if pattern_templates.template_groups %}
            {% include "pattern_library/pattern_group.html" with groups=pattern_templates.template_groups %}
        {% endif %}
        <ul class="list list--grandchild">
            {% for template in pattern_templates.templates_stored %}
            <li class="list__item">
                <a class="list__item-link" href="{% url 'pattern_library:display_pattern' template.origin.template_name %}" id="{{ template.origin.template_name }}">
                    {{ template.pattern_name }}
                </a>
            </li>
            {% endfor %}
        </ul>
    </li>
    {% endfor %}
</ul>